### ISSUE TITLE
CollaboraOnline menues get overlayed by frame menu from NC

### ISSUE THREAD

**Issue by budachst** [nextcloud/richdocuments#138]
### Steps to reproduce
1. update CollaboraOnline to 1.12.37
2. open any richtext document
3. the editor's menu will be overlayed by the former menu of the frame

### Expected behaviour
remove the remnants of the frame menu and have the CollaboraOnline menues be accessible
### Actual behaviour
The CollaboraOnline menues are overlayed and not accessible. Instead you can click on the home Icon usuallly found in the folder view frame, which in turn will make the folder contents "appear" in the document editor. Tried in Chrome and FF.

## Server configuration detail

**Operating system:** Linux 4.9.0-3-amd64 #1 SMP Debian 4.9.30-2+deb9u5 (2017-09-19) x86_64

**Webserver:** Apache/2.4.25 (Debian) (apache2handler)

**Database:** mysql 10.1.26

**PHP version:** 7.0.19-1
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, apache2handler, mysqlnd, PDO, xml, apcu, apc, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, igbinary, json, ldap, exif, mysqli, pdo_mysql, Phar, posix, readline, redis, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Zend OPcache

**Nextcloud version:** 13.0.0 Beta 1 - 13.0.0.6

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** unknown

<details><summary>Signing status</summary>

Array
</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - activity: 2.6.1
 - admin_audit: 1.3.0
 - apporder: 0.4.0
 - bookmarks: 0.10.1
 - calendar: 1.5.6
 - comments: 1.3.0
 - contacts: 2.0.1
 - dav: 1.4.5
 - deck: 0.2.7
 - federatedfilesharing: 1.3.1
 - federation: 1.3.0
 - files: 1.8.0
 - files_pdfviewer: 1.2.0
 - files_sharing: 1.5.0
 - files_texteditor: 2.5.1
 - files_trashbin: 1.3.0
 - files_versions: 1.6.0
 - files_videoplayer: 1.2.0
 - firstrunwizard: 2.2.1
 - gallery: 18.0.0
 - groupfolders: 1.1.0
 - issuetemplate: 0.3.0
 - logreader: 2.0.0
 - lookup_server_connector: 1.1.0
 - nextcloud_announcements: 1.2.0
 - notifications: 2.1.0
 - oauth2: 1.1.0
 - passman: 2.1.4
 - password_policy: 1.3.0
 - previewgenerator: 1.0.7
 - provisioning_api: 1.3.0
 - richdocuments: 1.12.37
 - serverinfo: 1.3.0
 - sharebymail: 1.3.0
 - survey_client: 1.1.0
 - systemtags: 1.3.0
 - theming: 1.4.1
 - twofactor_backupcodes: 1.2.3
 - twofactor_totp: 1.3.1
 - twofactor_u2f: 1.4.0
 - updatenotification: 1.3.0
 - user_ldap: 1.3.1
 - workflowengine: 1.3.0
Disabled:
 - encryption
 - files_external
 - user_external

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "***REMOVED SENSITIVE VALUE***"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "https:\/\/cloud.stephanbudach.de",
    "dbtype": "mysql",
    "version": "13.0.0.6",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "logtimezone": "GMT+2",
    "installed": true,
    "ldapIgnoreNamingRules": false,
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpmode": "smtp",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "25",
    "loglevel": "3",
    "htaccess.RewriteBase": "\/",
    "filelocking.enabled": "true",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "memcache.local": "\\OC\\Memcache\\APCu",
    "trashbin_retention_obligation": "auto",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 6379
    },
    "maintenance": false,
    "updater.release.channel": "beta",
    "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
    "mail_smtpauth": 1,
    "mail_smtpauthtype": "LOGIN",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "theme": "",
    "logfile": "\/var\/log\/nextcloud\/nextcloud.log",
    "log_rotate_size": 262144000,
    "log_type": "file"
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

<details><summary>LDAP configuration (delete this part if not used)</summary>
+-------------------------------+---------------------------------------------+
| Configuration                 | s01                                         |
+-------------------------------+---------------------------------------------+
| hasMemberOfFilterSupport      | 1                                           |
| hasPagedResultSupport         |                                             |
| homeFolderNamingRule          | attr:uid                                    |
| lastJpegPhotoLookup           | 0                                           |
| ldapAgentName                 |                                             |
| ldapAgentPassword             | ***                                         |
| ldapAttributesForGroupSearch  | cn;apple-generateduid                       |
| ldapAttributesForUserSearch   | mail;cn                                     |
| ldapBackupHost                |                                             |
| ldapBackupPort                |                                             |
| ldapBase                      | dc=***REMOVED SENSITIVE VALUE***                      |
| ldapBaseGroups                | cn=groups,dc=***REMOVED SENSITIVE VALUE***            |
| ldapBaseUsers                 | cn=users,dc=***REMOVED SENSITIVE VALUE***             |
| ldapCacheTTL                  | 6000                                        |
| ldapConfigurationActive       | 1                                           |
| ldapDefaultPPolicyDN          |                                             |
| ldapDynamicGroupMemberURL     |                                             |
| ldapEmailAttribute            | mail                                        |
| ldapExperiencedAdmin          | 1                                           |
| ldapExpertUUIDGroupAttr       |                                             |
| ldapExpertUUIDUserAttr        |                                             |
| ldapExpertUsernameAttr        | uid                                         |
| ldapGidNumber                 | gidNumber                                   |
| ldapGroupDisplayName          | cn                                          |
| ldapGroupFilter               | (&(|(objectclass=posixGroup)))              |
| ldapGroupFilterGroups         |                                             |
| ldapGroupFilterMode           | 0                                           |
| ldapGroupFilterObjectclass    | posixGroup                                  |
| ldapGroupMemberAssocAttr      | memberUid                                   |
| ldapHost                      | ***REMOVED SENSITIVE VALUE***              |
| ldapIgnoreNamingRules         |                                             |
| ldapLoginFilter               | (&(|(objectclass=inetOrgPerson))(uid=%uid)) |
| ldapLoginFilterAttributes     |                                             |
| ldapLoginFilterEmail          | 1                                           |
| ldapLoginFilterMode           | 0                                           |
| ldapLoginFilterUsername       | 1                                           |
| ldapNestedGroups              | 0                                           |
| ldapOverrideMainServer        |                                             |
| ldapPagingSize                | 5000                                        |
| ldapPort                      | 389                                         |
| ldapQuotaAttribute            |                                             |
| ldapQuotaDefault              |                                             |
| ldapTLS                       | 0                                           |
| ldapUserDisplayName           | cn                                          |
| ldapUserDisplayName2          |                                             |
| ldapUserFilter                | (|(objectclass=person))                     |
| ldapUserFilterGroups          |                                             |
| ldapUserFilterMode            | 1                                           |
| ldapUserFilterObjectclass     | person                                      |
| ldapUuidGroupAttribute        | auto                                        |
| ldapUuidUserAttribute         | auto                                        |
| turnOffCertCheck              | 0                                           |
| turnOnPasswordChange          | 0                                           |
| useMemberOfToDetectMembership | 1                                           |
+-------------------------------+---------------------------------------------+</details>

## Client configuration

**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0

**Operating system:** 
macOS HighSierra

**Comment by timar** [comment]
Is it a new problem with 1.12.37 that was not present with earlier versions?

**Comment by budachst** [comment]
Not that I am aware of. I am quite sure, that I checked CollaboraOnline after installing NC13.

**Comment by joergmschulz** [comment]
I can confirm the issue, and can confirm that the issue came up immedieately after installing the most recent richdocuments version for NC13 beta1.

**Comment by budachst** [comment]
This is what this looks like on my NC13, when opening any richtext document. As you can see, the menues get overlayed by some content from the former data.

![bildschirmfoto 2017-11-29 um 08 55 31](https://user-images.githubusercontent.com/10184884/33364100-3effb51a-d4e3-11e7-8878-bf8715e13e56.png)

**Comment by timar** [comment]
Fixed in richdocuments 1.12.38.

**Comment by joergmschulz** [comment]
not really: 
<img width="1154" alt="grafik" src="https://user-images.githubusercontent.com/6523646/33382033-f305bba4-d51f-11e7-82e6-801e90ec3dc1.png">

**Comment by budachst** [comment]
Yeah… still doesn't work for me either.

**Comment by joergmschulz** [comment]
Fixed in richdocuments 1.12.39

**Comment by budachst** [comment]
Yes! That did it! Thanks a lot!!

**Comment by silanea** [comment]
Unfortunately this issue is not fixed for me.
- NC 13.0.0beta4
- CODE latest docker image
- richdocuments 1.12.39
![screenshot](https://user-images.githubusercontent.com/436502/34651667-3ee42d4a-f3d3-11e7-8acb-388a19dce7c3.png)
