### ISSUE TITLE
Collabora changes modified date of file even if it wasn't saved

### ISSUE THREAD

**Issue by peterbo** [nextcloud/richdocuments#180]
### Steps to reproduce
1. Open a Collabora Online enabled filetype (e.g. xls), do not save, just close it again (via the red cross in the top right)

### Expected behaviour
The "modified date" of the file should not change, because no change has been made to the file.

### Actual behaviour
The modified date changes (to now), a file change activity is logged and a new version is created.

### Server configuration
**Operating system**:
Debian Wheezy
**Web server:**
Apache / nGinx
**Database:**
MySQL
**PHP version:**
7.0
**Nextcloud version:** (see Nextcloud admin page)
NC13, Collabora Online (App) 2.0.3, Collabora Office 5.3-39, LOOLWSD 3.0
**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh install
**Where did you install Nextcloud from:**
Official Download page
**Signing status:**
<details>
<summary>Signing status</summary>
No errors have been found.
</details>

**Are you using encryption:** yes

**Comment by thebearon** [comment]
This should be fixed with 3.1, please give it a try with the new version.

**Comment by peterbo** [comment]
Unfortunately, it's still reproducible with docker image LOOLWSD 3.1.0, LoKit 5.3-41, Collabora Online App 2.0.3

![code-version](https://user-images.githubusercontent.com/1018973/37101027-cf743ea2-2224-11e8-882f-94778cdc722c.JPG)

**Comment by thebearon** [comment]
It didn't happen with my samples. However, certain files might open flagged as changed, can you give it a try with the latest desktop LibreOffice version? If it happens there as well, please open a bug report in [LibreOffice bugzilla](https://bugs.documentfoundation.org/), with a sample file attached.

**Comment by peterbo** [comment]
Indeed this seems to only be happening with this one file (xls) (modified date is updated when file was opened/closed without modifying). I'll test this with the latest LibreOffice version as well. Other xls(x), docs, etc. files are not modified when opened.

Leaving this comment here for reference if anybody else experiences this problem.

Thank you for your help!
