### ISSUE TITLE
Date in Collabora only displayed in U.S-Format instead of German Format

### ISSUE THREAD

**Issue by kangaroo72** [nextcloud/richdocuments#185]
Hi,

I don't know, if it's right here ...

Nextcloud (German), CODE 3.0 (German), but when opening an Excel-Sheet with German dates inside (e.g. 31.03.2018) is displayed as 3/31/2018 ...

Is that an issue??

**Comment by thebearon** [comment]
When you write Nextcloud (German), does it mean your user language is set to German? Because that's what determines locale at the moment.

**Comment by ETrko** [comment]
same issue for me, shared document without any direct login access to nextcloud with browser settings in german, shows date format in english.

document was created in german format with excel and saved + uploaded

**Comment by unclepipsNC** [comment]
I am having the same problem with English UK.

I am running Nextcloud 14.0.4 with CODE versions LOOLWSD 3.4.1 LOKit Collabora Office 5.3-60.

In Nextcloud my user settings language is set to English (British English) and Locale is set to English (United Kingdom).

The excel file I uploaded was written in British UK format.

Even when I highlight the cells and check the format settings for those cells, it says English (UK) as the Language, and when I select the correct FORMAT the display does not reflect the settings I have chosen!

![image](https://user-images.githubusercontent.com/28535672/49118769-7f0ac680-f29d-11e8-8bd5-7816c2006778.png)
![image](https://user-images.githubusercontent.com/28535672/49118777-87630180-f29d-11e8-8b45-a4553f4a9226.png)
![image](https://user-images.githubusercontent.com/28535672/49118808-b4171900-f29d-11e8-9482-5eb1535d0b9a.png)

**Comment by juliushaertl** [comment]
I cannot reproduce this anymore with the latest CODE from docker and Nextcloud 15. Can you all please check with the latest version?

**Comment by unclepipsNC** [comment]
I am still on v14.04 of Nextcloud. However, just updated Collabora to 3.1.1 and the issue is fixed :-)

**Comment by brtptrs** [comment]
With LOOLWSD 3.4.0 and LOKit 5.3-57 we still have this problem which CODE version that would compare to I#m not sure.

![z_screenshot_20190118_001](https://user-images.githubusercontent.com/8102905/51390102-985a2180-1b2e-11e9-966a-5837ee938c5f.png)

**Comment by beedaddy** [comment]
I have this problem with nextcloud 17.0.1, LOOLWSD 4.0.8 and LOKit 6.0-29. Language and locale in Nextcloud are set to German, but date format in Collabora is US.

![image](https://user-images.githubusercontent.com/3264939/69148658-0ff13800-0ad5-11ea-9bae-bd51e7fe76a9.png)

**Comment by rob7xiv** [comment]
![Wrong Language in German Date](https://user-images.githubusercontent.com/6482568/84496104-a2913880-acac-11ea-89d7-c2f988a47dbb.png)
![collabora version](https://user-images.githubusercontent.com/6482568/84496123-a9b84680-acac-11ea-9457-a9be1387d99f.png)
Hello, I have the same prob.
Even the Language of the Months are Wrong.
German Standard is YY.MM.YYYY.
Chines , English, Persian, ... works.

Nextcloud is V. 18.0.4. not selfhosted.
Selfhosted Ubuntu 20 all charsets are installed.
de_DE.UTF-8 ist System Standard.

**Comment by rob7xiv** [comment]
ok nvm, I over read this sentence:

**This is the minimal installation, without localizations. For full installation install ‘collaboraoffice*’ packages.**

after I apt-get update && apt-get install collaboraoffice*
Its work.
