### ISSUE TITLE
Comments containing Umlauts don't work

### ISSUE THREAD

**Issue by TobiasReich** [nextcloud/richdocuments#2485]
Even with the latest version when creating comments that contain (german) umlauts (like Ä Ö Ü ...) the comments are broken.
They tend to disappear and cause trouble. Anyone who can confirm that?

Steps to repdoduce:

1. Open a new text document (odt)
2. Write a text (here even umlauts and accents work)
3. make a comment containting anything like (Ä Ö Ü ß...)
4. the comment disappears afterwards

**Comment by Raudius** [comment]
Hi,

What version of Collabora Online are you using?

I believe this issue is fixed in the latest collabora release. Tested with 22.05.6.3.

**Comment by juliushaertl** [comment]
Thanks for reporting. Let's close this as a duplicate of the relevant upstream issue https://github.com/CollaboraOnline/online/issues/4732 so in case this is still an issue with the latest release, please head over there :)
