### ISSUE TITLE
Loading screen hides public username field

### ISSUE THREAD

**Issue by rullzer** [nextcloud/richdocuments#280]
1. userA shares a file via link with write permissions
2. userB opens link

Right now userB just sees a spinning icon

This is because while loading we hide the building of the UI. But we should still allow the user to enter a username on the public page.

**Comment by Peac** [comment]
I still have this issue with 3.0.1.

I shared a folder with someone via link (with write permissions) and he only saw the field for the user name shortly. It was immediately replaced by the spinning wheel which runs endlessly.

**Comment by Peac** [comment]
I fixed it.

My document.js was like in 4830f6c and I changed it to 159c17d.
Now it is working again.

**Comment by fifh** [comment]
The same for me. Thank you @Peac, I did the same change and it works now.
So it seems that the patch https://github.com/nextcloud/richdocuments/pull/281 doesn't fix the bug.

**Comment by thebearon** [comment]
Hm, I don't see this bug, the Nickname field shows indefinitely. Are you using NC 14.0.3 as well?

**Comment by Peac** [comment]
Same here, NC 14.0.3 and Richdocuments 3.0.1

**Comment by fifh** [comment]
With some more tests, some more information : the endlessly spinning wheel appears only when you share a folder, with write permission.
If you share a document, it works.
So to reproduce : 
- share a folder with write permission via public link (or with an email address, same result obviously)
- insert some documents in there (whatever the format : ODF, OpenXML...)
- in another browser, open the shared folder via the public link 
- click on one of the documents

-> the field for the user name appears quickly and then is replaced by a endlessly spinning wheel.

**Comment by fifh** [comment]
tested with Richdocuments 3.0.2, same result

**Comment by rullzer** [comment]
Can one of you share a document via public link (with write permissions) with me? As I can't reproduce this on any of my instances.

**Comment by fifh** [comment]
@rullzer Done, using a email address roeland@fa...nl

**Comment by rullzer** [comment]
Should be fixed with https://github.com/nextcloud/richdocuments/pull/293

**Comment by fifh** [comment]
@rullzer yes ! It works for me.

**Comment by Peac** [comment]
Same here. Thank you for the fix.

**Comment by rullzer** [comment]
Perfect. I'll release a new patch release soon.
