### ISSUE TITLE
Option to limit app usage to group

### ISSUE THREAD

**Issue by rugk** [nextcloud/richdocuments#30]
I'd like it if this app could have the option "Only allow specific groups to use this app".

**Comment by timar** [comment]
The feature used to be there, but somehow it became a victim of a large refactoring. We need to restore it.

**Comment by pranavk** [comment]
@timar If I remember correctly, the option was all about allowing specific groups to edit the documents, and opening the document in readonly mode for others. There was nothing like limiting the app usage to specific groups.

**Comment by timar** [comment]
@pranavk You are right, I did not read the error report carefully. However, what I wrote was true. We used to have the option about allowing specific groups to edit the documents and we need to restore this. Viewing is allowed for all, even for anonymous users through a shared link in Nextcloud.

**Comment by pranavk** [comment]
So, this is not a bug then, but a feature request.

**Comment by timar** [comment]
Fixed by pull request #135

**Comment by scroom** [comment]
Problem still persists. In the actual version of Collabora Online I can't limit the access to the app to a specific group.

**Comment by juliushaertl** [comment]
Group limitation is not part of the apps management, since richdocuments needs file access, which forbids limiting it to groups though the nextcloud API. However there is an additional setting in the richdocuments settings to limit the app to specific groups.
