### ISSUE TITLE
Since version 8.2.4 dark mode is broken and renders calc unusable

### ISSUE THREAD

**Issue by Polve** [nextcloud/richdocuments#3700]
**Describe the bug**
Since version 8.2.4 dark mode is broken and renders calc unusable: everything is black/dark and unreadable
![image](https://github.com/nextcloud/richdocuments/assets/1634436/67a2e177-07c0-4cfc-ba6c-0b93e31d408c)

**To Reproduce**
All the details in this bug report: https://github.com/CollaboraOnline/online/issues/8721

I open it here because maybe there is not the right place and this bug render the service completely unusable with dark mode on

**Comment by mejo-** [comment]
@Polve can you still reproduce this with Nextcloud 28.0.6, richdocuments app 8.4.2 and Collabora Online 24.04? I ran into the same problem before, but was not able to reproduce this any longer, so I wonder whether this got fixed in the meantime.

**Comment by Polve** [comment]
Tried right now with nextcloud 27.1.9, nextcloud office app 8.2.10 and coolwsd 24.04.3.1, but the problem persists

**Comment by Polve** [comment]
I upgraded to nextcloud 28.0.6 and rich documents 8.3.7 and the problem is still there :-(

I will try to upgrade to NC 29

**Comment by Polve** [comment]
Ok, tried also with NC 29.0.1 and richdocuments 8.4.2: same problem, unfortunately :-( 

But at least you forced me to upgrade :-D

**Comment by Polve** [comment]
I don't know how to make you reproduce: I run two installations that always worked fine until that upgrade, and in both installations I have the same problem.
Maybe it's something special about my configs, but they should be pretty standard.

I can just tell you that I have the dark theme both on my (ubuntu) desktop and firefox, and the problem is there.

To reproduce I suppose I should try a new installation from scratch but this could take me some time.

**Comment by AgentSmith83** [comment]
I have the exact same issue with Nextcloud 29.0.2 and richdocuments 8.4.2. Has not worked since around Nextcloud version 28.0.5. I am also running a vanilla nextcloud install. Dark mode is completely unusuable.

**Comment by Polve** [comment]
For me latest coolwsd (24.04.4.1) just fixed the problem!

I updated literally minutes ago and closed https://github.com/CollaboraOnline/online/issues/8721

**Comment by mejo-** [comment]
Great to hear @Polve. For me the issue got solved with latest Collabora updates as well.

**Comment by AgentSmith83** [comment]
I still have the same issue and my server is 100% up-to-date. What version of coolwsd did you update to? I see that 24.4.201 which was released on May 15 is the version that I have had for a few weeks at least and it didn't resolve anything.

**Comment by Polve** [comment]
I'm using coolwsd version 24.04.4.1-1 debian package running on debian 11 (bullseye)

**Comment by AgentSmith83** [comment]
The Collabora Online/CODE/coolwsd June 18 release fixed the issue for me. So that is 24.4.402 or cp-24.04.4-2

**Comment by djmaze** [comment]
For me, this is still a problem with Nextcloud 31 and coolwsd 24.04.13.2 (git hash [ded56d8ff7](https://github.com/CollaboraOnline/online/commits/ded56d8ff7), current docker image `collabora/code`).

**Comment by Polve** [comment]
Did you try to reset default templates?

Anyway for me since a few releases collabora sheet ignores my dark theme and uses white background...

**Comment by djmaze** [comment]
Uhm, how would I do that? This is a fresh installation and I did not mess with any template stuff at all.

**Comment by Polve** [comment]
fresh install of nextcloud or collabora?

**Comment by djmaze** [comment]
Collabora. It's just the `collabora/code` container.

**Comment by Polve** [comment]
For what I know the template files are on the nextcloud server: that's why they need to be updated
