### ISSUE TITLE
Revision access from collabora not working with documents in personal folder

### ISSUE THREAD

**Issue by hriekehof** [nextcloud/richdocuments#389]
**Describe the bug**
When i have document in my personal folder in Nextcloud on the first level, i also cannot use the revisions tab from the collabora program. It just shows two empty pages and gets stuck when you want to switch revisions from there.

**To Reproduce**
1. Go to a document in your folder like a simple odt and create a few versions.
2. Click on file and show revisions
3. See error

**Expected behavior**
i would like to scroll through the different revisions. Select them and view them.

**Screenshots**
When you click. here
![image](https://user-images.githubusercontent.com/9348635/52468944-73375c80-2b8a-11e9-984c-c672c5e31eb1.png)

This happens
![image](https://user-images.githubusercontent.com/9348635/52468970-864a2c80-2b8a-11e9-867a-1ff511d3d41b.png)

**Client details:**
 - OS: Win10
 - Browser chrome
 - Version 71
 - Device: desktop

## Server details

**Operating system**: docker image

**Web server:** apache

**Database:** mariadb10

**PHP version:** 7.2

**Nextcloud version:** 15.0.4

**Version of the richdocuments app** 3.2.0

**Version of Collabora online** 4

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
{"reqId":"uekRdBJ3P1dkQBa7M1nM","level":3,"time":"2019-02-08T08:59:43+00:00","remoteAddr":"172.19.0.13","user":"Riekehof","app":"PHP","method":"GET","url":"/settings/admin/richdocuments?y=297&x=210","message":"Undefined index: delete at /var/www/html/custom_apps/richdocuments/templates/admin.php#84","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.96 Safari/537.36","version":"15.0.4.0","id":"5c5d49418c7e4"}

[PHP] Error: Undefined index: preview at /var/www/html/custom_apps/richdocuments/templates/admin.php#81

GET /settings/admin/richdocuments?y=297&x=210
from 172.19.0.13 by Riekehof at 2019-02-08T08:59:43+00:00
```
</details>

**Comment by juliushaertl** [comment]
Are there any logs in your browser console when trying to access the revision history?

<details>
<summary>How to access your browser console (Click to expand)</summary>

# Chrome
- Press either CTRL + SHIFT + J to open the “console” tab of the Developer Tools.
- Alternative method:
    1. Press either CTRL + SHIFT + I or F12 to open the Developer Tools.
    2. Click the “console” tab.

# Safari
- Press CMD + ALT + I to open the Web Inspector.
- See Chrome’s step 2. (Chrome and Safari have pretty much identical dev tools.)

# IE9
1. Press F12 to open the developer tools.
2. Click the “console” tab.

# Firefox
- Press CTRL + SHIFT + K to open the Web console (COMMAND + SHIFT + K on Macs).
- or, if Firebug is installed (recommended):
    1. Press F12 to open Firebug.
    2. Click on the “console” tab.

# Opera
1. Press CTRL + SHIFT + I to open Dragonfly.
2. Click on the “console” tab.
</details>

**Comment by hriekehof** [comment]
Yes. Sorry i forgot that. This it what appears in my Chrome console:

```
core.js:7 JQMIGRATE: Migrate is installed, version 1.4.0
/core/preview?fileId=2002&c=50aac6931451a42fbbff9f12f9c21295&x=250&y=250&forceIcon=0:1 Failed to load resource: the server responded with a status of 404 (Not Found)
nextcloud.xxx.xxx.local/:1 Unchecked runtime.lastError: The message port closed before a response was received.
core.js:7 JQMIGRATE: Migrate is installed, version 1.4.0
merged-template-prepend.js:3711 Deprecation warning: tipsy is deprecated. Use tooltip instead.
jQuery.fn.tipsy @ merged-template-prepend.js:3711
(anonymous) @ documents.js:988
j @ core.js:2
fireWith @ core.js:2
ready @ core.js:2
I @ core.js:2
documents.js:548 Waiting for page to render…
bundle.js:22 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
request_JSON @ bundle.js:22
String_ctr.(anonymous function) @ bundle.js:22
(anonymous) @ bundle.js:22
(anonymous) @ bundle.js:22
/core/preview?fileId=2002&c=50aac6931451a42fbbff9f12f9c21295&x=250&y=250&forceIcon=0:1 Failed to load resource: the server responded with a status of 404 (Not Found)
core.js:7 JQMIGRATE: Migrate is installed, version 1.4.0
merged-template-prepend.js:3711 Deprecation warning: tipsy is deprecated. Use tooltip instead.
jQuery.fn.tipsy @ merged-template-prepend.js:3711
documents.js:548 Waiting for page to render…
documents.js:445 Uncaught TypeError: Cannot read property 'get' of null
    at Object.addCurrentVersion (documents.js:445)
    at Object.showViewer (documents.js:367)
    at Object.showRevHistory (documents.js:424)
    at documents.js:678
DevTools failed to parse SourceMap: http://nextcloud.xxx.xxx.local/apps/notifications/js/notifications.js.map
```

**Comment by juliushaertl** [comment]
Should be fixed by #394

**Comment by hriekehof** [comment]
I tested the new version 3.2.1 on my installation and unfortunately i still get the same error. Blank version window. The error messages in the browser log are different.

```
core.js:7 JQMIGRATE: Migrate is installed, version 1.4.0
core.js:7 JQMIGRATE: Migrate is installed, version 1.4.0
VM254 indexTemplate:1 Refused to execute script from 'http://nextcloud.xxx.xxx.local/apps/files/' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
merged-template-prepend.js:3711 Deprecation warning: tipsy is deprecated. Use tooltip instead.
jQuery.fn.tipsy @ merged-template-prepend.js:3711
documents.js:548 Waiting for page to render…
bundle.js:22 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
request_JSON @ bundle.js:22
bundle.js:56 Uncaught TypeError: Cannot read property 'style' of undefined
    at NewClass._changeInteractions (bundle.js:56)
    at NewClass.fire (bundle.js:41)
    at NewClass._enterEditMode (bundle.js:55)
    at NewClass.setPermission (bundle.js:55)
    at NewClass._onMessage (bundle.js:41)
documents.js:445 Uncaught TypeError: Cannot read property 'get' of null
    at Object.addCurrentVersion (documents.js:445)
    at Object.showViewer (documents.js:367)
    at Object.showRevHistory (documents.js:424)
    at documents.js:678
DevTools failed to parse SourceMap: http://nextcloud.xxx.xxx.local/apps/notifications/js/notifications.js.map
```

**Comment by hriekehof** [comment]
@juliushaertl could you had a look at it ? With Version 3.2.1 the problem still remains in my case.

**Comment by juliushaertl** [comment]
@hriekehof Can you check again with the recent release 3.2.3 it should be fine.

**Comment by hriekehof** [comment]
Hi,

sorry i was in vacation last week. Version 3.2.3 seems to work fine for me now. 👍

**Comment by juliushaertl** [comment]
Thanks for reporting back :+1:

**Comment by hriekehof** [comment]
No problem. Thanks to all at nextcloud for this great work.  #387 would be so great too :)
