### ISSUE TITLE
cURL error 3: <url> malformed

### ISSUE THREAD

**Issue by bperel** [nextcloud/richdocuments#58]
### Steps to reproduce
1. Open any document file on my instance

### Expected behaviour
I should see my document

### Actual behaviour
I see an error on the page and in the error log

### Server configuration

**Operating system**:
Ubuntu 16.04.2

**Web server:**
Apache 2.2

**Database:**
MariaDB

**PHP version:**
7.0.15

**Nextcloud version:** (see Nextcloud admin page)
12.0 beta 4

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from 12.0 beta 2 but same issue existed

**Where did you install Nextcloud from:**
PHP install script

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - activity: 2.5.2
  - admin_audit: 1.2.0
  - bruteforcesettings: 1.0.2
  - calendar: 1.5.2
  - comments: 1.2.0
  - dav: 1.3.0
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_external: 1.3.0
  - files_pdfviewer: 1.1.1
  - files_retention: 1.1.2
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - firstrunwizard: 2.1
  - gallery: 17.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.1
  - notifications: 2.0.0
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - richdocuments: 1.12.27
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - survey_client: 1.0.0
  - systemtags: 1.2.0
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - workflowengine: 1.2.0
Disabled:
  - documents
  - encryption
  - music
  - user_external
  - user_ldap
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

```json
{
    "system": {
        "instanceid": "ocd4udorn6gg",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "...",
            "....no-ip.org",
            "....ddns.net",
            "....homenet.org"
        ],
        "datadirectory": "\/var\/www\/nextcloud\/data",
        "overwrite.cli.url": "http:\/\/...\/nextcloud",
        "dbtype": "mysql",
        "version": "12.0.0.21",
        "logtimezone": "UTC",
        "installed": true,
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "trashbin_retention_obligation": "auto",
        "appstore.experimental.enabled": true,
        "dbname": "owncloud",
        "dbhost": "127.0.0.1",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "preview_libreoffice_path": "\/usr\/bin\/libreoffice",
        "updater.secret": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "updater.release.channel": "beta",
        "mail_from_address": "...",
        "mail_smtpmode": "php",
        "mail_smtpauthtype": "LOGIN",
        "mail_domain": "..."
    }
}
```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** Letsencrypt certificate

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:**
Chrome 58

**Operating system:**
Windows 7

#### Web server error log
<details>
<summary>Web server error log</summary>
None
</details>

#### Nextcloud log (data/nextcloud.log)
(JSON formated and duplicate back-slashes removed)
```
{
    "reqId": "SB6dWRTt22YYFP6XJwRx",
    "level": 3,
    "time": "2017-05-19T07:41:56+00:00",
    "remoteAddr": "...",
    "user": "...",
    "app": "richdocuments",
    "method": "GET",
    "url": "/nextcloud/index.php/apps/richdocuments/index?fileId=167904&requesttoken=%2F21lU39ibZspQfU6IrTk7MpBSBfR6pPj%2Bdrq2QTM9Iw%3D%3AyiQsF0ZNXqNqN94VScej2YEKCiLk38mNnLGv6kWdrOU%3D",
    "message": "Exception: {\"Exception\":\"GuzzleHttp\Exception\RequestException\",\"Message\":\"cURL error 3: <url> malformed\",\"Code\":0,\"Trace\":\"#0 /var/www/html/nextcloud/3rdparty/guzzlehttp/guzzle/src/RequestFsm.php(103): GuzzleHttp\Exception\RequestException::wrapException(Object(GuzzleHttp\Message\Request), Object(GuzzleHttp\Ring\Exception\RingException))n#1 /var/www/html/nextcloud/3rdparty/guzzlehttp/guzzle/src/RequestFsm.php(132): GuzzleHttp\RequestFsm->__invoke(Object(GuzzleHttp\Transaction))n#2 /var/www/html/nextcloud/3rdparty/react/promise/src/FulfilledPromise.php(25): GuzzleHttp\RequestFsm->GuzzleHttp\{closure}(Array)n#3 /var/www/html/nextcloud/3rdparty/guzzlehttp/ringphp/src/Future/CompletedFutureValue.php(55): React\Promise\FulfilledPromise->then(Object(Closure), NULL, NULL)n#4 /var/www/html/nextcloud/3rdparty/guzzlehttp/guzzle/src/Message/FutureResponse.php(43): GuzzleHttp\Ring\Future\CompletedFutureValue->then(Object(Closure), NULL, NULL)n#5 /var/www/html/nextcloud/3rdparty/guzzlehttp/guzzle/src/RequestFsm.php(134): GuzzleHttp\Message\FutureResponse::proxy(Object(GuzzleHttp\Ring\Future\CompletedFutureArray), Object(Closure))n#6 /var/www/html/nextcloud/3rdparty/guzzlehttp/guzzle/src/Client.php(165): GuzzleHttp\RequestFsm->__invoke(Object(GuzzleHttp\Transaction))n#7 /var/www/html/nextcloud/3rdparty/guzzlehttp/guzzle/src/Client.php(125): GuzzleHttp\Client->send(Object(GuzzleHttp\Message\Request))n#8 /var/www/html/nextcloud/lib/private/Http/Client/Client.php(138): GuzzleHttp\Client->get('/hosting/discov...', Array)n#9 /var/www/html/nextcloud/apps/richdocuments/lib/WOPI/DiscoveryManager.php(84): OC\Http\Client\Client->get('/hosting/discov...')n#10 /var/www/html/nextcloud/apps/richdocuments/lib/WOPI/Parser.php(41): OCA\Richdocuments\WOPI\DiscoveryManager->get()n#11 /var/www/html/nextcloud/apps/richdocuments/lib/TokenManager.php(94): OCA\Richdocuments\WOPI\Parser->getUrlSrc('application/vnd...')n#12 /var/www/html/nextcloud/apps/richdocuments/lib/Controller/DocumentController.php(108): OCA\Richdocuments\TokenManager->getToken(*** sensitive parameters replaced ***)n#13 [internal function]: OCA\Richdocuments\Controller\DocumentController->index('167904')n#14 /var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php(160): call_user_func_array(Array, Array)n#15 /var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php(90): OC\AppFramework\Http\Dispatcher->executeController(Object(OCA\Richdocuments\Controller\DocumentController), 'index')n#16 /var/www/html/nextcloud/lib/private/AppFramework/App.php(114): OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\Richdocuments\Controller\DocumentController), 'index')n#17 /var/www/html/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php(47): OC\AppFramework\App::main('OCA\\Richdocumen...', 'index', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)n#18 [internal function]: OC\AppFramework\Routing\RouteActionHandler->__invoke(Array)n#19 /var/www/html/nextcloud/lib/private/Route/Router.php(299): call_user_func(Object(OC\AppFramework\Routing\RouteActionHandler), Array)n#20 /var/www/html/nextcloud/lib/base.php(1000): OC\Route\Router->match('/apps/richdocum...')n#21 /var/www/html/nextcloud/index.php(40): OC::handleRequest()n#22 {main}\",\"File\":\"/var/www/html/nextcloud/3rdparty/guzzlehttp/guzzle/src/Exception/RequestException.php\",\"Line\":51}",
    "userAgent": "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.81 Safari/537.36",
    "version": "12.0.0.21"
}
```

#### Browser log
<details>
<summary>Browser log</summary>
No console error.

Page rendering :
![chrome_2017-05-19_10-25-50](https://cloud.githubusercontent.com/assets/1484692/26239638/1eafb88a-3c7e-11e7-9178-7fec656adbf0.png)

Page request : 
![chrome_2017-05-19_10-27-55](https://cloud.githubusercontent.com/assets/1484692/26239639/1eb00f92-3c7e-11e7-8930-9bfc4ff056dd.png)

</details>

**Comment by ckruse** [comment]
Happens for me as well:

~~~
GuzzleHttp\Exception\RequestException: cURL error 3: <url> malformed

    /var/www/html/3rdparty/guzzlehttp/guzzle/src/RequestFsm.php - line 104: GuzzleHttp\Exception\RequestException wrapException(Object(GuzzleHttp\Message\Request), Object(GuzzleHttp\Ring\Exception\RingException))
    /var/www/html/3rdparty/guzzlehttp/guzzle/src/RequestFsm.php - line 132: GuzzleHttp\RequestFsm->__invoke(Object(GuzzleHttp\Transaction))
    /var/www/html/3rdparty/react/promise/src/FulfilledPromise.php - line 25: GuzzleHttp\RequestFsm->GuzzleHttp\{closure}(Array)
    /var/www/html/3rdparty/guzzlehttp/ringphp/src/Future/CompletedFutureValue.php - line 55: React\Promise\FulfilledPromise->then(Object(Closure), NULL, NULL)
    /var/www/html/3rdparty/guzzlehttp/guzzle/src/Message/FutureResponse.php - line 43: GuzzleHttp\Ring\Future\CompletedFutureValue->then(Object(Closure), NULL, NULL)
    /var/www/html/3rdparty/guzzlehttp/guzzle/src/RequestFsm.php - line 135: GuzzleHttp\Message\FutureResponse proxy(Object(GuzzleHttp\Ring\Future\CompletedFutureArray), Object(Closure))
    /var/www/html/3rdparty/guzzlehttp/guzzle/src/Client.php - line 165: GuzzleHttp\RequestFsm->__invoke(Object(GuzzleHttp\Transaction))
    /var/www/html/3rdparty/guzzlehttp/guzzle/src/Client.php - line 125: GuzzleHttp\Client->send(Object(GuzzleHttp\Message\Request))
    /var/www/html/lib/private/Http/Client/Client.php - line 138: GuzzleHttp\Client->get('/hosting/discov...', Array)
    /var/www/html/apps/richdocuments/lib/WOPI/DiscoveryManager.php - line 84: OC\Http\Client\Client->get('/hosting/discov...')
    /var/www/html/apps/richdocuments/lib/WOPI/Parser.php - line 41: OCA\Richdocuments\WOPI\DiscoveryManager->get()
    /var/www/html/apps/richdocuments/lib/TokenManager.php - line 94: OCA\Richdocuments\WOPI\Parser->getUrlSrc('application/vnd...')
    /var/www/html/apps/richdocuments/lib/Controller/DocumentController.php - line 108: OCA\Richdocuments\TokenManager->getToken(*** sensitive parameters replaced ***)
    [internal function] OCA\Richdocuments\Controller\DocumentController->index('140')
    /var/www/html/lib/private/AppFramework/Http/Dispatcher.php - line 160: call_user_func_array(Array, Array)
    /var/www/html/lib/private/AppFramework/Http/Dispatcher.php - line 90: OC\AppFramework\Http\Dispatcher->executeController(Object(OCA\Richdocuments\Controller\DocumentController), 'index')
    /var/www/html/lib/private/AppFramework/App.php - line 114: OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\Richdocuments\Controller\DocumentController), 'index')
    /var/www/html/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47: OC\AppFramework\App main('DocumentControl...', 'index', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
    [internal function] OC\AppFramework\Routing\RouteActionHandler->__invoke(Array)
    /var/www/html/lib/private/Route/Router.php - line 299: call_user_func(Object(OC\AppFramework\Routing\RouteActionHandler), Array)
    /var/www/html/lib/base.php - line 1000: OC\Route\Router->match('/apps/richdocum...')
    /var/www/html/index.php - line 40: OC handleRequest()
    {main}
~~~

Anything one can do?

**Comment by ErmoM** [comment]
i have same error .

>  GuzzleHttp\Exception\RequestException:`
>  cURL error 3: <url> malformed
> /var/www/html/nextcloud/3rdparty/guzzlehttp/guzzle/src/RequestFsm.php - line 103: GuzzleHttp\Exception\RequestException wrapException(Object(GuzzleHttp\Message\Request), Object(GuzzleHttp\Ring\Exception\RingException))
> /var/www/html/nextcloud/3rdparty/guzzlehttp/guzzle/src/RequestFsm.php - line 132: GuzzleHttp\RequestFsm->__invoke(Object(GuzzleHttp\Transaction))
> /var/www/html/nextcloud/3rdparty/react/promise/src/FulfilledPromise.php - line 25: GuzzleHttp\RequestFsm->GuzzleHttp\{closure}(Array)
> /var/www/html/nextcloud/3rdparty/guzzlehttp/ringphp/src/Future/CompletedFutureValue.php - line 55: React\Promise\FulfilledPromise->then(Object(Closure), NULL, NULL)
> /var/www/html/nextcloud/3rdparty/guzzlehttp/guzzle/src/Message/FutureResponse.php - line 43: GuzzleHttp\Ring\Future\CompletedFutureValue->then(Object(Closure), NULL, NULL)
> /var/www/html/nextcloud/3rdparty/guzzlehttp/guzzle/src/RequestFsm.php - line 134: GuzzleHttp\Message\FutureResponse proxy(Object(GuzzleHttp\Ring\Future\CompletedFutureArray), Object(Closure))
> /var/www/html/nextcloud/3rdparty/guzzlehttp/guzzle/src/Client.php - line 165: GuzzleHttp\RequestFsm->__invoke(Object(GuzzleHttp\Transaction))
> /var/www/html/nextcloud/3rdparty/guzzlehttp/guzzle/src/Client.php - line 125: GuzzleHttp\Client->send(Object(GuzzleHttp\Message\Request))
> /var/www/html/nextcloud/lib/private/Http/Client/Client.php - line 138: GuzzleHttp\Client->get('/hosting/discov...', Array)
> /var/www/html/nextcloud/apps/richdocuments/lib/WOPI/DiscoveryManager.php - line 84: OC\Http\Client\Client->get('/hosting/discov...')
> /var/www/html/nextcloud/apps/richdocuments/lib/WOPI/Parser.php - line 41: OCA\Richdocuments\WOPI\DiscoveryManager->get()
> /var/www/html/nextcloud/apps/richdocuments/lib/TokenManager.php - line 94: OCA\Richdocuments\WOPI\Parser->getUrlSrc('application/vnd...')
> /var/www/html/nextcloud/apps/richdocuments/lib/Controller/DocumentController.php - line 108: OCA\Richdocuments\TokenManager->getToken(*** sensitive parameters replaced ***)
> [internal function] OCA\Richdocuments\Controller\DocumentController->index('563')
> /var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 160: call_user_func_array(Array, Array)
> /var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 90: OC\AppFramework\Http\Dispatcher->executeController(Object(OCA\Richdocuments\Controller\DocumentController), 'index')
> /var/www/html/nextcloud/lib/private/AppFramework/App.php - line 114: OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\Richdocuments\Controller\DocumentController), 'index')
> /var/www/html/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47: OC\AppFramework\App main('OCA\\Richdocumen...', 'index', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
> [internal function] OC\AppFramework\Routing\RouteActionHandler->__invoke(Array)
> /var/www/html/nextcloud/lib/private/Route/Router.php - line 299: call_user_func(Object(OC\AppFramework\Routing\RouteActionHandler), Array)
> /var/www/html/nextcloud/lib/base.php - line 1000: OC\Route\Router->match('/apps/richdocum...')
> /var/www/html/nextcloud/index.php - line 40: OC handleRequest()
> {main}

**Comment by thebearon** [comment]
What do you see when you try to open this page: https://<Collabora Online server>/hosting/discovery

**Comment by ArtyV** [comment]
I get the XML page

**Comment by thebearon** [comment]
@ArtyV, you have this bug, too?

**Comment by ArtyV** [comment]
Yes,, I think 

`InvalidArgumentException: Unable to parse malformed url: https:///XXXXXl:9980/hosting/discovery
/var/www/html/nextcloud/3rdparty/guzzlehttp/guzzle/src/Message/Request.php - line 70: GuzzleHttp\Url fromString('https ///server...')
/var/www/html/nextcloud/3rdparty/guzzlehttp/guzzle/src/Message/Request.php - line 42: GuzzleHttp\Message\Request->setUrl('https ///server...')
/var/www/html/nextcloud/3rdparty/guzzlehttp/guzzle/src/Message/MessageFactory.php - line 85: GuzzleHttp\Message\Request->__construct('GET', 'https ///server...', Array, NULL, Array)
/var/www/html/nextcloud/3rdparty/guzzlehttp/guzzle/src/Client.php - line 120: GuzzleHttp\Message\MessageFactory->createRequest('GET', 'https ///server...', Array)
/var/www/html/nextcloud/3rdparty/guzzlehttp/guzzle/src/Client.php - line 125: GuzzleHttp\Client->createRequest('GET', 'https ///server...', Array)
/var/www/html/nextcloud/lib/private/Http/Client/Client.php - line 138: GuzzleHttp\Client->get('https ///server...', Array)
/var/www/html/nextcloud/apps/richdocuments/lib/WOPI/DiscoveryManager.php - line 84: OC\Http\Client\Client->get('https ///server...')
/var/www/html/nextcloud/apps/richdocuments/lib/WOPI/Parser.php - line 41: OCA\Richdocuments\WOPI\DiscoveryManager->get()
/var/www/html/nextcloud/apps/richdocuments/lib/TokenManager.php - line 94: OCA\Richdocuments\WOPI\Parser->getUrlSrc('application/vnd...')
/var/www/html/nextcloud/apps/richdocuments/lib/Controller/DocumentController.php - line 108: OCA\Richdocuments\TokenManager->getToken(*** sensitive parameters replaced ***)
[internal function] OCA\Richdocuments\Controller\DocumentController->index('5094467')
/var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 160: call_user_func_array(Array, Array)
/var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 90: OC\AppFramework\Http\Dispatcher->executeController(Object(OCA\Richdocuments\Controller\DocumentController), 'index')
/var/www/html/nextcloud/lib/private/AppFramework/App.php - line 114: OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\Richdocuments\Controller\DocumentController), 'index')
/var/www/html/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47: OC\AppFramework\App main('OCA\\Richdocumen...', 'index', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
[internal function] OC\AppFramework\Routing\RouteActionHandler->__invoke(Array)
/var/www/html/nextcloud/lib/private/Route/Router.php - line 299: call_user_func(Object(OC\AppFramework\Routing\RouteActionHandler), Array)
/var/www/html/nextcloud/lib/base.php - line 1000: OC\Route\Router->match('/apps/richdocum...')
/var/www/html/nextcloud/index.php - line 40: OC handleRequest()
{main}`


I think mine may be slightly differnet, not sure.

**Comment by aronpapp** [comment]
Same error on:
- debian 9.0
- apache 2.4.25 (self-signed certs)
- php 7.0.19
- postgresql 9.6
- nextcloud 12.0.0 (from zip)
- collabora online 1.12.33 (from docker)

```
{"reqId":"Zx9K5LKCGXmyco5jWazm","level":3,"time":"2017-07-05T23:47:46+00:00",
"remoteAddr":"192.168.1.65","user":"xy","app":"richdocuments","method":"GET",
"url":"\/nextcloud\/index.php\/apps\/richdocuments\/index?fileId=164&requesttoken=WoY6w%2BpyBeW85NJ0GUDVue8dOyJiUyJkjz6t7lC47bA%3D%3AKfxRt785f7Lmo5gDSi29zJ9OWWsBN1Uxyw3%2BngPfj%2BI%3D",
"message":"Exception: {\"Exception\":\"GuzzleHttp\Exception\RequestException\",
\"Message\":\"cURL error 3: <url> malformed\",\"Code\":0,\"Trace\":\"#0 
/var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/RequestFsm.php(103): GuzzleHttp\Exception\RequestException::wrapException(Object(GuzzleHttp\Message\Request), Object(GuzzleHttp\Ring\Exception\RingException))\\n#1 
/var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/RequestFsm.php(132): GuzzleHttp\RequestFsm->__invoke(Object(GuzzleHttp\Transaction))\\n#2 
/var/www/nextcloud/3rdparty/react/promise/src/FulfilledPromise.php(25): GuzzleHttp\RequestFsm->GuzzleHttp\{closure}(Array)\\n#3 
/var/www/nextcloud/3rdparty/guzzlehttp/ringphp/src/Future/CompletedFutureValue.php(55): React\Promise\FulfilledPromise->then(Object(Closure), NULL, NULL)\\n#4 
/var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Message/FutureResponse.php(43): GuzzleHttp\Ring\Future\CompletedFutureValue->then(Object(Closure), NULL, NULL)\\n#5 
/var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/RequestFsm.php(134): GuzzleHttp\Message\FutureResponse::proxy(Object(GuzzleHttp\Ring\Future\CompletedFutureArray), Object(Closure))\\n#6 
/var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Client.php(165): GuzzleHttp\RequestFsm->__invoke(Object(GuzzleHttp\Transaction))\\n#7 
/var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Client.php(125): GuzzleHttp\Client->send(Object(GuzzleHttp\Message\Request))\\n#8 
/var/www/nextcloud/lib/private/Http/Client/Client.php(138): GuzzleHttp\Client->get('/hosting/discov...', Array)\\n#9 
/var/www/nextcloud/apps/richdocuments/lib/WOPI/DiscoveryManager.php(84): OC\Http\Client\Client->get('/hosting/discov...')\\n#10 
/var/www/nextcloud/apps/richdocuments/lib/WOPI/Parser.php(41): OCA\Richdocuments\WOPI\DiscoveryManager->get()\\n#11 
/var/www/nextcloud/apps/richdocuments/lib/TokenManager.php(117): OCA\Richdocuments\WOPI\Parser->getUrlSrc('application/vnd...')\\n#12 
/var/www/nextcloud/apps/richdocuments/lib/Controller/DocumentController.php(108): OCA\Richdocuments\TokenManager->getToken(*** sensitive parameters replaced ***)\\n#13 [internal function]: OCA\Richdocuments\Controller\DocumentController->index('164')\\n#14 
/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php(160): call_user_func_array(Array, Array)\\n#15 
/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php(90): OC\AppFramework\Http\Dispatcher->executeController(Object(OCA\Richdocuments\Controller\DocumentController), 'index')\\n#16 
/var/www/nextcloud/lib/private/AppFramework/App.php(114): OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\Richdocuments\Controller\DocumentController), 'index')\\n#17 
/var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php(47): OC\AppFramework\App::main('OCA\\Richdocumen...', 'index', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)\\n#18 [internal function]: OC\AppFramework\Routing\RouteActionHandler->__invoke(Array)\\n#19 
/var/www/nextcloud/lib/private/Route/Router.php(299): call_user_func(Object(OC\AppFramework\Routing\RouteActionHandler), Array)\\n#20 
/var/www/nextcloud/lib/base.php(1000): OC\Route\Router->match('/apps/richdocum...')\\n#21 
/var/www/nextcloud/index.php(40): OC::handleRequest()\\n#22 {main}\",\"File\":\"
/var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Exception/RequestException.php\",\"Line\":51}","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/59.0.3071.115 Safari\/537.36","version":"12.0.0.29"}
```

**Comment by t507** [comment]
Same prob here. Fresh install NC 12.0
- Debian 8
- nginx 1.6.2
- php 5.6.30
- MySQL 5.5.55
- Collabora Online 1.12.33

> {"reqId":"Fw9Zzcp4XBhOgd5Ha3g4","level":3,"time":"2017-07-14T13:35:36+00:00","remoteAddr":"192.168.x.x","user":"xy","app":"richdocuments","method":"GET","url":"\/apps\/richdocuments\/index?fileId=203&requesttoken=Xahr4cyyQmySBszD1qKJ1FmC37M7v4mSbETws3UJCxo%3D%3AHsUogI3zFQThX5myodH%2FsDy0jutxlMTYBQu%2B3TJRbXg%3D","message":"Exception: {\"Exception\":\"GuzzleHttp\Exception\RequestException\",\"Message\":\"cURL error 3: <url> malformed\",\"Code\":0,\"Trace\":\"#0 /mnt/usb3/nextcloud/3rdparty/guzzlehttp/guzzle/src/RequestFsm.php(104): GuzzleHttp\Exception\RequestException::wrapException(Object(GuzzleHttp\Message\Request), Object(GuzzleHttp\Ring\Exception\RingException))\\n#1 /mnt/usb3/nextcloud/3rdparty/guzzlehttp/guzzle/src/RequestFsm.php(132): GuzzleHttp\RequestFsm->__invoke(Object(GuzzleHttp\Transaction))\\n#2 /mnt/usb3/nextcloud/3rdparty/react/promise/src/FulfilledPromise.php(25): GuzzleHttp\RequestFsm->GuzzleHttp\{closure}(Array)\\n#3 /mnt/usb3/nextcloud/3rdparty/guzzlehttp/ringphp/src/Future/CompletedFutureValue.php(55): React\Promise\FulfilledPromise->then(Object(Closure), NULL, NULL)\\n#4 /mnt/usb3/nextcloud/3rdparty/guzzlehttp/guzzle/src/Message/FutureResponse.php(43): GuzzleHttp\Ring\Future\CompletedFutureValue->then(Object(Closure), NULL, NULL)\\n#5 /mnt/usb3/nextcloud/3rdparty/guzzlehttp/guzzle/src/RequestFsm.php(135): GuzzleHttp\Message\FutureResponse::proxy(Object(GuzzleHttp\Ring\Future\CompletedFutureArray), Object(Closure))\\n#6 /mnt/usb3/nextcloud/3rdparty/guzzlehttp/guzzle/src/Client.php(165): GuzzleHttp\RequestFsm->__invoke(Object(GuzzleHttp\Transaction))\\n#7 /mnt/usb3/nextcloud/3rdparty/guzzlehttp/guzzle/src/Client.php(125): GuzzleHttp\Client->send(Object(GuzzleHttp\Message\Request))\\n#8 /mnt/usb3/nextcloud/lib/private/Http/Client/Client.php(138): GuzzleHttp\Client->get('/hosting/discov...', Array)\\n#9 /mnt/usb3/nextcloud/apps/richdocuments/lib/WOPI/DiscoveryManager.php(84): OC\Http\Client\Client->get('/hosting/discov...')\\n#10 /mnt/usb3/nextcloud/apps/richdocuments/lib/WOPI/Parser.php(41): OCA\Richdocuments\WOPI\DiscoveryManager->get()\\n#11 /mnt/usb3/nextcloud/apps/richdocuments/lib/TokenManager.php(117): OCA\Richdocuments\WOPI\Parser->getUrlSrc('application/vnd...')\\n#12 /mnt/usb3/nextcloud/apps/richdocuments/lib/Controller/DocumentController.php(108): OCA\Richdocuments\TokenManager->getToken(*** sensitive parameters replaced ***)\\n#13 [internal function]: OCA\Richdocuments\Controller\DocumentController->index('203')\\n#14 /mnt/usb3/nextcloud/lib/private/AppFramework/Http/Dispatcher.php(160): call_user_func_array(Array, Array)\\n#15 /mnt/usb3/nextcloud/lib/private/AppFramework/Http/Dispatcher.php(90): OC\AppFramework\Http\Dispatcher->executeController(Object(OCA\Richdocuments\Controller\DocumentController), 'index')\\n#16 /mnt/usb3/nextcloud/lib/private/AppFramework/App.php(114): OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\Richdocuments\Controller\DocumentController), 'index')\\n#17 /mnt/usb3/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php(47): OC\AppFramework\App::main('DocumentControl...', 'index', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)\\n#18 [internal function]: OC\AppFramework\Routing\RouteActionHandler->__invoke(Array)\\n#19 /mnt/usb3/nextcloud/lib/private/Route/Router.php(299): call_user_func(Object(OC\AppFramework\Routing\RouteActionHandler), Array)\\n#20 /mnt/usb3/nextcloud/lib/base.php(1000): OC\Route\Router->match('/apps/richdocum...')\\n#21 /mnt/usb3/nextcloud/index.php(40): OC::handleRequest()\\n#22 {main}\",\"File\":\"/mnt/usb3/nextcloud/3rdparty/guzzlehttp/guzzle/src/Exception/RequestException.php\",\"Line\":51}","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:38.9) Gecko\/20100101 Goanna\/2.1 Firefox\/38.9 PaleMoon\/26.3.3","version":"12.0.0.29"}

No other issues experienced so far on NC12.

**Comment by gruelfin** [comment]
i have the same problem

**Comment by S-Kis** [comment]
Same problem. 

I got Ubuntu 16.04 LTS, Nextcloud 12.0.1 stable and Collabora Online Version 1.12.34.

No one can help?

**Comment by albirs** [comment]
same here 
Nextcloud 12.0.2 stable and Collabora Online Version 1.12.34.

**Comment by tmssss** [comment]
same here

nginx: Version: 1.10.3-1+deb9u1
debian: 9.1
php: 7.0.19-1
mariadb: 10.1.26-0+deb9u1
    /var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/RequestFsm.php - line 103: GuzzleHttp\Exception\RequestException wrapException(Object(GuzzleHttp\Message\Request), Object(GuzzleHttp\Ring\Exception\RingException))
    /var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/RequestFsm.php - line 132: GuzzleHttp\RequestFsm->__invoke(Object(GuzzleHttp\Transaction))
    /var/www/nextcloud/3rdparty/react/promise/src/FulfilledPromise.php - line 25: GuzzleHttp\RequestFsm->GuzzleHttp\{closure}(Array)
    /var/www/nextcloud/3rdparty/guzzlehttp/ringphp/src/Future/CompletedFutureValue.php - line 55: React\Promise\FulfilledPromise->then(Object(Closure), NULL, NULL)
    /var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Message/FutureResponse.php - line 43: GuzzleHttp\Ring\Future\CompletedFutureValue->then(Object(Closure), NULL, NULL)
    /var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/RequestFsm.php - line 134: GuzzleHttp\Message\FutureResponse proxy(Object(GuzzleHttp\Ring\Future\CompletedFutureArray), Object(Closure))
    /var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Client.php - line 165: GuzzleHttp\RequestFsm->__invoke(Object(GuzzleHttp\Transaction))
    /var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Client.php - line 125: GuzzleHttp\Client->send(Object(GuzzleHttp\Message\Request))
    /var/www/nextcloud/lib/private/Http/Client/Client.php - line 138: GuzzleHttp\Client->get('/hosting/discov...', Array)
    /var/www/nextcloud/apps/richdocuments/lib/WOPI/DiscoveryManager.php - line 84: OC\Http\Client\Client->get('/hosting/discov...')
    /var/www/nextcloud/apps/richdocuments/lib/WOPI/Parser.php - line 41: OCA\Richdocuments\WOPI\DiscoveryManager->get()
    /var/www/nextcloud/apps/richdocuments/lib/TokenManager.php - line 117: OCA\Richdocuments\WOPI\Parser->getUrlSrc('application/vnd...')
    /var/www/nextcloud/apps/richdocuments/lib/Controller/DocumentController.php - line 108: OCA\Richdocuments\TokenManager->getToken(*** sensitive parameters replaced ***)
    [internal function] OCA\Richdocuments\Controller\DocumentController->index('365')
    /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 160: call_user_func_array(Array, Array)
    /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 90: OC\AppFramework\Http\Dispatcher->executeController(Object(OCA\Richdocuments\Controller\DocumentController), 'index')
    /var/www/nextcloud/lib/private/AppFramework/App.php - line 114: OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\Richdocuments\Controller\DocumentController), 'index')
    /var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47: OC\AppFramework\App main('OCA\\Richdocumen...', 'index', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
    [internal function] OC\AppFramework\Routing\RouteActionHandler->__invoke(Array)
    /var/www/nextcloud/lib/private/Route/Router.php - line 299: call_user_func(Object(OC\AppFramework\Routing\RouteActionHandler), Array)
    /var/www/nextcloud/lib/base.php - line 1004: OC\Route\Router->match('/apps/richdocum...')
    /var/www/nextcloud/index.php - line 48: OC handleRequest()
    {main}

**Comment by Mywk** [comment]
Same problem, or at least it seems like it:

nginx: Version: 1.10.3-1+deb9u1
debian: 9.1
php: 7.0.19-1
mariadb: 10.1.26-0+deb9u1

`{  
   "reqId":"...",
   "level":3,
   "time":"2017-09-21T13:03:06+00:00",
   "remoteAddr":"...",
   "user":"...",
   "app":"richdocuments",
   "method":"GET",
   "url":"\/index.php\/apps\/richdocuments\/index?fileId=109&requesttoken=qePkI8RbHDStsTuVjNVhI0E8168bWdzjD5grlaCqWFg%3D%3A44CQFZZ0WWzXwn7D5YIqbiNroulZb76JdaB%2B8%2FbSGjQ%3D",
   "message":"Exception: {\"Exception\":\"GuzzleHttp\\\\Exception\\\\RequestException\",\"Message\":\"cURL error 3: <url> malformed\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/RequestFsm.php(103): GuzzleHttp\\\\Exception\\\\RequestException::wrapException(Object(GuzzleHttp\\\\Message\\\\Request), Object(GuzzleHttp\\\\Ring\\\\Exception\\\\RingException))\\n#1 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/RequestFsm.php(132): GuzzleHttp\\\\RequestFsm->__invoke(Object(GuzzleHttp\\\\Transaction))\\n#2 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/react\\\/promise\\\/src\\\/FulfilledPromise.php(25): GuzzleHttp\\\\RequestFsm->GuzzleHttp\\\\{closure}(Array)\\n#3 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/guzzlehttp\\\/ringphp\\\/src\\\/Future\\\/CompletedFutureValue.php(55): React\\\\Promise\\\\FulfilledPromise->then(Object(Closure), NULL, NULL)\\n#4 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/Message\\\/FutureResponse.php(43): GuzzleHttp\\\\Ring\\\\Future\\\\CompletedFutureValue->then(Object(Closure), NULL, NULL)\\n#5 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/RequestFsm.php(134): GuzzleHttp\\\\Message\\\\FutureResponse::proxy(Object(GuzzleHttp\\\\Ring\\\\Future\\\\CompletedFutureArray), Object(Closure))\\n#6 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/Client.php(165): GuzzleHttp\\\\RequestFsm->__invoke(Object(GuzzleHttp\\\\Transaction))\\n#7 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/Client.php(125): GuzzleHttp\\\\Client->send(Object(GuzzleHttp\\\\Message\\\\Request))\\n#8 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Http\\\/Client\\\/Client.php(138): GuzzleHttp\\\\Client->get('\\\/hosting\\\/discov...', Array)\\n#9 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/richdocuments\\\/lib\\\/WOPI\\\/DiscoveryManager.php(84): OC\\\\Http\\\\Client\\\\Client->get('\\\/hosting\\\/discov...')\\n#10 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/richdocuments\\\/lib\\\/WOPI\\\/Parser.php(41): OCA\\\\Richdocuments\\\\WOPI\\\\DiscoveryManager->get()\\n#11 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/richdocuments\\\/lib\\\/TokenManager.php(117): OCA\\\\Richdocuments\\\\WOPI\\\\Parser->getUrlSrc('application\\\/vnd...')\\n#12 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/richdocuments\\\/lib\\\/Controller\\\/DocumentController.php(108): OCA\\\\Richdocuments\\\\TokenManager->getToken(*** sensitive parameters replaced ***)\\n#13 [internal function]: OCA\\\\Richdocuments\\\\Controller\\\\DocumentController->index('109')\\n#14 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(160): call_user_func_array(Array, Array)\\n#15 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(90): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Richdocuments\\\\Controller\\\\DocumentController), 'index')\\n#16 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(114): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Richdocuments\\\\Controller\\\\DocumentController), 'index')\\n#17 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main('OCA\\\\\\\\Richdocumen...', 'index', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#18 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#19 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Route\\\/Router.php(299): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#20 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/base.php(1004): OC\\\\Route\\\\Router->match('\\\/apps\\\/richdocum...')\\n#21 \\\/var\\\/www\\\/nextcloud\\\/index.php(48): OC::handleRequest()\\n#22 {main}\",\"File\":\"\\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/Exception\\\/RequestException.php\",\"Line\":51}",
   "userAgent":"Mozilla\/5.0 (Windows NT 10.0; WOW64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/60.0.3112.105 Safari\/537.36 Vivaldi\/1.92.917.43",
   "version":"12.0.3.3"
}`

**Comment by hdayi** [comment]
Same problem here

Converting file works fine.
When I click on the file to edit I get the error but when I click in "Open in ONLYOFFICE" link which is in three dot menu it works. 

Those two have different URL's. 
The faulty ones URL is:  https://blabla.com/remote.php/webdav/Documents/About.docx
The working one is: https://blabla.com/apps/files/?dir=/Documents&fileid=2383#

I guess something goes wrong in remote.php file.

I have added a picture of three dots menu I have mentioned above to be more clear.

My nextcloud version is: 12.0.3
onlyoffice app is: 1.1.4

![hata](https://user-images.githubusercontent.com/7522907/30899467-a98b6944-a368-11e7-86d9-b6542c2c3346.jpg)

**Comment by Mywk** [comment]
## Fixed by completely uninstalling and re-installing, the issue is not related to nextcloud or richdocuments directly.

When you're installing Collabora Online Server, **make sure you use the correct path**!!

Simply quoting from the [installation page](https://nextcloud.com/collaboraonline/):

> ...make sure to replace "cloud.nextcloud.com" with the host that your own Nextcloud runs on. Also make sure to escape all dots with double backslashes (\), since this string will be evaluated as a regular expression (and your bash 'eats' the first backslash.) If you want to use the docker container with more than one Nextcloud, you'll need to use 'domain=cloud\\.nextcloud\\.com\|second\\.nexcloud\\.com' instead. (All hosts are separated by \|.)

To remove Collabora online find the process on docker, stop it and remove it:
```
sudo docker ps -a

CONTAINER ID        IMAGE              ...
52f43cc1583a        collabora/code     ...

sudo docker stop 52f43cc1583a

sudo docker rm 52f43cc1583a
```
Then you can simply re-install:
```
docker run -t -d -p 127.0.0.1:9980:9980 -e 'domain=submain\\.domain\\.com' --restart always --cap-add MKNOD collabora/code
```

**Comment by kundansingh27feb** [comment]
After ldap configuration i am getting the same issue. Any solution for this?

**Comment by ammbrteam** [comment]
Same problem here... almost a year later and still not fixed? Sheesh...

Anyone have any suggestions.

Fresh Ubuntu 16.04 LTS install with NC 12 running behind an NGINX reverse proxy on another box.

**Comment by froschwelle** [comment]
Same Problem here as well. 
Using NC snap on Ubuntu 16.04 LTS (VM1) and Collabora on a different machine (VM2). I also tried Onlyoffice. Same problem... 
Funnily all this is as well behind a Nginx reverse proxy on VM3.

**Comment by SHITianhao** [comment]
Same problem on

- Nextcloud 13 
- NGINX
- ubuntu 16.04

**Comment by XelionIO** [comment]
Same issue with

- Nextcloud 13
- Nginx
- Debian 9

**Comment by digulla** [comment]
@XelionIO Which part of the setup is broken?

I'm using snap and then add the app to nextcloud from the web. How do I pass the domain name to CODE?

**Comment by digulla** [comment]
Okay, with Nextcloud 13 and CODE 2.0.4, there is a config page for Collabora Online at .../index.php/settings/admin/richdocuments

Copy and paste the server part from the location bar into the text field and click "Apply".

For example, if the location bar of your browser shows https://foo.local/index.php/settings/admin/richdocuments, then use `https://foo.local`

**Comment by Flofus** [comment]
My browser gives me an 404 error

`/index.php/apps/richdocuments/ajax/admin.php 
Failed to load resource: the server responded with a status of 404 ()`

**Comment by jeaye** [comment]
This happened to me because I didn't realize installing Collabora Online required a separate docker container running the service. I thought clicking "Install" within Nextcloud would give me the app which does the trick. Nope. Instead, one must follow the install steps here: https://nextcloud.com/collaboraonline/

It's a bit finnicky to get set up and ultimately required restarting docker (the service) and the container a couple of times. Seems like it's running well now though!

**Comment by McDAlexander** [comment]
For anyone seeing this in the future. I ran into this issue with the cURL error 3 while trying to access word documents from Nextcloud in Collabora. I found that I also had Office Online Integration also enabled on my server, but without an actual instance running anywhere. Once I disabled the Office Online Integration, I was able to open my documents in Collabora (having Collabora run in another Docker which Nextcloud is pointed to using collabora.mydomain.com)

**Comment by u451f** [comment]
I confirm having seen this issue with OnlyOffice + Office Online enabled. Disabling OfficeOnline and relying on OnlyOffice did the trick for me.
