### ISSUE TITLE
Documents cannot be saved since v3.5.1

### ISSUE THREAD

**Issue by supremesyntax** [nextcloud/richdocuments#781]
**Describe the bug**

Documents can't be saved since v3.5.1

**To Reproduce**
1. Create new document (docx or odt) via (+) icon
2. Open docuement
3. Write anything
4. Try to save document -> No permission

**Expected behavior**
Document should be saved

**Screenshots**
![Bildschirmfoto vom 2020-01-14 10-23-55](https://user-images.githubusercontent.com/25605570/72331339-f244e700-36af-11ea-9374-9eaa19e1c1e5.png)

**Client details:**
 - OS: all
 - Browser: all

## Server details

**Operating system**: Ubuntu 16.04.6

**Web server:** Apache 2.4.18-2ubuntu3.14

**PHP version:** 7.0.33-0ubuntu0.16.04.7 

**Nextcloud version:** 15.0.14

**Version of the richdocuments app** v3.5.1

**Version of Collabora Online** 4.2.0 (Docker container)

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
{"reqId":"*deleted*","level":3,"time":"2020-01-14T09:34:41+01:00","remoteAddr":"*deleted*","user":"*deleted*","app":"index","method":"POST","url":"/index.php/apps/richdocuments/wopi/files/*deleted*/contents?access_token=*deleted*&access_token_ttl=0","message":{"Exception":"TypeError","Message":"Return value of OCA\\Richdocuments\\Service\\UserScopeService::setFilesystemScope() must be an instance of OCA\\Richdocuments\\Service\\void, none returned","Code":0,"Trace":[{"file":"/var/www/nextcloud/apps/richdocuments/lib/Controller/WopiController.php","line":449,"function":"setFilesystemScope","class":"OCA\\Richdocuments\\Service\\UserScopeService","type":"->","args":["*deleted*"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":166,"function":"putFile","class":"OCA\\Richdocuments\\Controller\\WopiController","type":"->","args":["*deleted*","*deleted*"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":99,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Richdocuments\\Controller\\WopiController"},"putFile"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":118,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Richdocuments\\Controller\\WopiController"},"putFile"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Richdocuments\\Controller\\WopiController","putFile",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"fileId":"*deleted*","_route":"richdocuments.wopi.putFile"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"fileId":"*deleted*","_route":"richdocuments.wopi.putFile"}]},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":297,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"fileId":"*deleted*","_route":"richdocuments.wopi.putFile"}]},{"file":"/var/www/nextcloud/lib/base.php","line":987,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/apps/richdocuments/wopi/files/400659_oc0l3917unjy/contents"]},{"file":"/var/www/nextcloud/index.php","line":42,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/nextcloud/apps/richdocuments/lib/Service/UserScopeService.php","Line":67,"CustomMessage":"--"},"userAgent":"LOOLWSD WOPI Agent 4.2.0","version":"15.0.14.1","id":"*deleted*"}
```
</details>

**Comment by supremesyntax** [comment]
Just pulled latest collabora docker image 4.2.0.3, same error...
Is this a richdocuments error or a collabora problem?

**Comment by supremesyntax** [comment]
i went back to **3.5.0** and saving files is working again!

**Comment by t0mcat1337** [comment]
I have a similar issue, not sure, if it is the same cause but have some more informations. First of all my Versions:

Collabora App: 3.5.1
Versions App: 1.9.0 (seems to have sth. to do with it, see below)
CODE docker image: 4.2.0.3
OS: Ubuntu 18.04
Nextcloud: 16.0.3.0

When the Versions App is enabled, the file is on an external storage (SMB in my case) which is shared with another NC User, then this user isn't able to save the file and gets the error Msg from above.
In the Nextcloud Log is this:

 ```
[index] Error: Error: Call to a member function getId() on boolean at <<closure>>
0. /srv/www/wolke.leitold.koeln/apps/files_versions/lib/Hooks.php line 61
    OCA\Files_Versions\Storage::store("/01_HOME/Privat ... s")
 1. /srv/www/wolke.leitold.koeln/lib/private/legacy/hook.php line 106
    OCA\Files_Versions\Hooks::write_hook({path: "/01_HOME ... e})
 2. /srv/www/wolke.leitold.koeln/lib/private/Files/View.php line 617
    OC_Hook::emit("OC_Filesystem", "write", {path: "/01_HOME ... e})
 3. /srv/www/wolke.leitold.koeln/lib/private/Files/View.php line 659
    OC\Files\View->emit_file_hooks_pre(true, "/snoopy/files/0 ... s", true)
 4. /srv/www/wolke.leitold.koeln/lib/private/Files/Node/File.php line 66
    OC\Files\View->file_put_contents("/snoopy/files/0 ... s", null)
 5. /srv/www/wolke.leitold.koeln/apps/richdocuments/lib/Controller/WopiController.php line 453
    OC\Files\Node\File->putContent(null)
 6. /srv/www/wolke.leitold.koeln/apps/richdocuments/lib/Controller/WopiController.php line 623
    OCA\Richdocuments\Controller\WopiController->OCA\Richdocuments\Controller\{closure}("*** sensitive parameters replaced ***")
 7. /srv/www/wolke.leitold.koeln/apps/richdocuments/lib/Controller/WopiController.php line 454
    OCA\Richdocuments\Controller\WopiController->retryOperation(Closure {})
 8. /srv/www/wolke.leitold.koeln/lib/private/AppFramework/Http/Dispatcher.php line 166
    OCA\Richdocuments\Controller\WopiController->putFile("2198057", "4LMCC65tjkxLoCsvzajQhYey5m56Boot")
 9. /srv/www/wolke.leitold.koeln/lib/private/AppFramework/Http/Dispatcher.php line 99
    OC\AppFramework\Http\Dispatcher->executeController(OCA\Richdocument ... {}, "putFile")
10. /srv/www/wolke.leitold.koeln/lib/private/AppFramework/App.php line 126
    OC\AppFramework\Http\Dispatcher->dispatch(OCA\Richdocument ... {}, "putFile")
11. /srv/www/wolke.leitold.koeln/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
    OC\AppFramework\App::main("OCA\\Richdocume ... r", "putFile", OC\AppFramework\ ... {}, {fileId: "219805 ... "})
12. <<closure>>
    OC\AppFramework\Routing\RouteActionHandler->__invoke({fileId: "219805 ... "})
13. /srv/www/wolke.leitold.koeln/lib/private/Route/Router.php line 297
    undefinedundefinedcall_user_func(OC\AppFramework\ ... {}, {fileId: "219805 ... "})
14. /srv/www/wolke.leitold.koeln/lib/base.php line 975
    OC\Route\Router->match("/apps/richdocum ... s")
15. /srv/www/wolke.leitold.koeln/index.php line 42
    OC::handleRequest()

POST /index.php/apps/richdocuments/wopi/files/2198057_oc0h5ha9hsy5/contents?access_token=4LMCC65tjkxLoCsvzajQhYey5m56Boot&access_token_ttl=0
from 192.168.41.1 by brina at 2020-01-17T21:06:14+01:00

```

This is in docker logs from the CODE Container:
```
wsd-00030-00237 2020-01-17 20:06:14.753981 [ docbroker_00d ] ERR  Unexpected response to WOPI::PutFile : 500Cannot save file to WOPI storage uri [https://cloud.domain.dom/index.php/apps/richdocuments/wopi/files/2198057_oc0h5ha9hsy5/contents?access_token=4LMCC65tjkxLoCsvzajQhYey5m56Boot&access_token_ttl=0]. Error: | wsd/Storage.cpp:1083
wsd-00030-00237 2020-01-17 20:06:14.754223 [ docbroker_00d ] ERR  Failed to save docKey [/index.php/apps/richdocuments/wopi/files/2198057_oc0h5ha9hsy5] to URI [https://cloud.domain.dom/index.php/apps/richdocuments/wopi/files/2198057_oc0h5ha9hsy5?access_token=4LMCC65tjkxLoCsvzajQhYey5m56Boot&access_token_ttl=0]. Notifying client.| wsd/DocumentBroker.cpp:1080
```



When disabling the Versions App everything works fine...

Found a similar ticket with the ONLYOFFICE App:
https://github.com/ONLYOFFICE/onlyoffice-nextcloud/issues/118

which seems to be solved with this commit:
https://github.com/ONLYOFFICE/onlyoffice-nextcloud/pull/162

After downgrading Collabora App to 3.5.0 everything works again even with enabled Version App....So perhaps this fix needs to be reviewed:
**Fix issue when shared files were not creating activity/version entries**

I hope these informations help to track down the issue...

**Comment by t-markmann** [comment]
Same issue here.
Workaround: create a file locally, upload it into the cloud. Then the file can be saved.

Hope it can be fixed soon.

**Comment by lgnch** [comment]
Same issue as reported in #780. A return to 3.5.0 is confirmed to work until a fix is implemented.

**Comment by t-markmann** [comment]
If you want to keep 3.5.1 because of other bugfixes and want to keep the Versions app, you can try out this MySQL trigger: 

```mysql
DELIMITER |
DROP TRIGGER IF EXISTS `temp-triggerWopiTemplate`|
CREATE TRIGGER `temp-triggerWopiTemplate`
BEFORE INSERT
ON `oc_richdocuments_wopi`
FOR EACH ROW
BEGIN
	IF (NEW.`template_id`!='0')
	THEN
		SET NEW.`template_id`='0';
	END IF;
END;
|
DELIMITER ;
```

It replaces the template id with 0. It's hacky but it works.

**Comment by juliushaertl** [comment]
Everyone who encounters the getId() log error, please give https://github.com/nextcloud/richdocuments/pull/805 a try.

The other issue when saving fails after creating them from a template, please upgrade to the latest Collabora version. That should fix the issue.

**Comment by resoli** [comment]
This affects a NC 15.0.14 instance I manage (reverting to richdocuments 3.5.0 fixes), but not other NC 17.0.2 installations.

**Comment by it25fg** [comment]
> The other issue when saving fails after creating them from a template, please upgrade to the latest Collabora version. That should fix the issue.
Which version do you refer to? I've seen this error with richdocuments 3.5.1 and loolwsd 4.0-2 which is the latest possible in a production system (updated some minutes ago).

**Comment by juliushaertl** [comment]
This should be fixed with the new 3.5.2 release.

**Comment by ashemsay** [comment]
Hello,

I'm on 3.5.2 and still experience this issue, though I never had any previous version, this is a first install. How can I install version 3.5.0 instead?

**Comment by lgnch** [comment]
If you are getting the error with no previous install then 3.5.0 will unlikely solve your issue. You will need to open a support ticket and post all your information as this is likely to be a permissions problem with your CODE install.

**Comment by pitchum** [comment]
> I'm on 3.5.2 and still experience this issue

FYI:
On a nextcloud v15 with richdocuments v3.5.2 and I had to manually install v3.5.0 to solve this.
On a nextcloud v17 with richdocuments v3.5.2 everything is fine.
